apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2 
  # deployment labels
  labels:
    purpose: ingress
    project: roboshop
    app: app2
spec:
  replicas: 2
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: ingress
      project: roboshop
      app: app2
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: ingress
        project: roboshop
        app: app2
    spec:
      containers:
      - name: app2 
        image: govardhanxo/app2:v1
      # ports:
      # - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2 
  labels:
    purpose: ingress
    project: roboshop
    app: app2
spec:
  selector:
    purpose: ingress
    project: roboshop
    app: app2
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2 
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:688372068521:certificate/2927062c-a85e-4ff7-9cad-f79660d2a7e2
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: govardhanxo
spec:
  ingressClassName: alb
  rules:
  - host: "app2.govardhanxo.site"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80 # app2 service port

